# Generated by Django 5.2.10 on 2026-01-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_team_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('admin', 'Adminstrator'), ('member', 'Member')], default='member'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittlere'), ('high', 'Hoch')], default='medium'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Zu Tätigen'), ('in_progress', 'In Bearbeitung'), ('done', 'Erledigt')], default='todo'),
        ),
    ]
