# Generated by Django 5.2.10 on 2026-01-13 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_membership_role_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_team_leader',
        ),
    ]
