# Generated by Django 5.2.10 on 2026-01-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('zu_tätigen', 'Zu Tätigen'), ('in_bearbeitung', 'In Bearbeitung'), ('erledigt', 'Erledigt')], default='todo'),
        ),
    ]
