# Generated by Django 5.2.10 on 2026-01-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittlere'), ('high', 'Hoch')], default='mittlere'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('zu_tätigen', 'Zu Tätigen'), ('in_bearbeitung', 'In Bearbeitung'), ('erledigt', 'Erledigt')], default='zu_tätigen'),
        ),
    ]
