# Generated by Django 5.2.10 on 2026-01-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('niedrig', 'Niedrig'), ('mittlere', 'Mittlere'), ('hoch', 'Hoch')], default='mittlere'),
        ),
    ]
